#Numbpy Basics

Creating a Numpy Arrey and Its Attributes

In [ ]:
#importing numpy librery
import numpy as np

#creating a list
my_list = [1, 2, 3, 4, 5]
#changing the list into a 1-D numpy array
my_array = np.array(my_list)

print(my_array)


#creating a 0-D numpy array
zero_array = np.array(42)
print(zero_array)

#In1stead a creating alist on aseperate variable we can directly pass a list to .arry()function like this
my_array = np. array([1,2,3,4,5])

#Printing a 1-D numpy arry
print(my_array)


#Lets create a 2-D array!
two_d_array = np.array([[1,2,3],[4,5,6]])
#Printing a 2d numpy array
print(two_d_array)

#Lets create a 3-D array!
three_d_array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
#Printing a 3d numpy array
print(three_d_array)


[1 2 3 4 5]
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Lets create an array and aee its attribures
my_array = np.array([[1,2,3],[4,5,6]])
print(my_array)     #Printing a array
print(my_array.ndim)    #Printing a dimension of array
print(my_array.shape)   #Printing a shape of array
print(my_array.size)    #Printing a size of array
print(my_array.dtype)   #Printing a type of the array

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


Accessing and manipulating array elements

In [ ]:
#Lets create a 1D array and print one of its elements
one_arr = np.array([1,2,3,4,5,6])
# To access an element, use square brackets [] with the index inside.
print(one_arr[4])

#Lets print using negetive indexing
print(one_arr[-2])


#Lets do for 2D array
two_arr = np.array([[1,2,3],[4,5,6]])
print(two_arr[1,2])

#Lets move to a 3D array
three_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_arr[1,1,2])
print(three_arr[1,0,0])

5
5
6
12
7


SLICING ARRAYS

###Some important slicing concepts
array[start:end]

array[start:end:steps]

In [ ]:
#slicing arrays from 0th to 8th index
my_array = np.array([1,2,3,4,5,6,7,8,9,10]) #1-D array
print(my_array[0:8])
print(my_array[3:9])

#Slicing with steps
my_new_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_new_array[0:9:2])
print(my_new_array[0:9:3])


#Slicing on a 2-D array
my_two_d = np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])
print(my_two_d[1,0:6])
print(my_two_d[0,3:6])


[1 2 3 4 5 6 7 8]
[4 5 6 7 8 9]
[1 3 5 7 9]
[1 4 7]
[10 11 12 13 14 15]
[4 5 6]


#CLASSWORK

In [ ]:
#create the array QN.1
my_list = np.array([7,14,21,28])
print(my_list)

#QN.2
two_d_array = np.array([[5,10,15],[20,25,30]])
print(two_d_array.shape)
# Correcting the print statement to access .ndim on the array first
print(two_d_array.ndim)



#QN.3. create 2D arrays of zeros with shape
zeros_array = np.zeros((2,3))
print(zeros_array)

#creating array from 0 to 12 with step of three
my_array = np.arange(0,12,3)
print(my_array)


#QN.4 Create nympy array and multiply it by 3
array = np.array([2,4,6,8,10])
result = array * 3
print(result)

#QN. 5 create numpy array print third element and slice from index 1 to 3
my_array = np.array([1,3,5,7,9,11])
print(my_array[2])
print(my_array[1:4])


[ 7 14 21 28]
(2, 3)
2
[[0. 0. 0.]
 [0. 0. 0.]]
[0 3 6 9]
[ 6 12 18 24 30]
5
[3 5 7]


H.W. - experiment with 3D SLICING

In [ ]:
#create 1D array from 2 to 10 (inclusive)
array = np.arange(2, 11)

#add 5 - each element
result = array + 5
print(result)



#create 2-Darray
two_d_array = np.array([[1, 3, 5], [2, 4, 6]])
first_row = two_d_array[0]

print("First row:", first_row)
print("Sum of first row:", row_sum)

[ 7  8  9 10 11 12 13 14 15]
First row: [1 3 5]
Sum of first row: 9
