#Linear Algebra for AI

#Working with Scalers and Vectors

In [ ]:
import numpy as np

scalar = 9
print(scalar)

vector = np.array([3,6,8,45,19])
print(vector)

scaled_vector = scalar *vector
print(scaled_vector)


9
[ 3  6  8 45 19]
[ 27  54  72 405 171]


In [ ]:
vector = np.array([4,7,9,12,19])
vector1 = np.array([5,8,9,11,34])

scaled_vector = vector + vector1
print(scaled_vector)

[ 9 15 18 23 53]


#Matric Creation and Simple Operation

In [ ]:

matrix1 = np.array([[1,2], [4,5]])
matrix2 = np.array([[2,3], [6,7]])

scaled_matrix = matrix1 + matrix2
print(scaled_matrix)


#Multiplication of matrix
matrix1 = np.array([[7,4],
                    [4,3]])
matrix2 = np.array([[3,9],
                    [6,6]])

scaled_matrix = matrix1 * matrix2
print(scaled_matrix)

[[ 3  5]
 [10 12]]
[[21 36]
 [24 18]]


In [ ]:
#Multiply 2 matrix

matrix1 = np.array([[3,5], [6,4]])
matrix2 = np.array([[3,7], [5,1]])

matmal = np.dot(matrix1,matrix2)
print(matmal)

[[34 26]
 [38 46]]


In [ ]:
#3/3 matrix

matrix1 = np.array([[3,5,4], [6,4,9], [7,2,2]])
matrix2 = np.array([[3,7,6], [5,1,2], [9,4,7]])

matmal = np.dot(matrix1,matrix2)
print(matmal)

[[ 70  42  56]
 [119  82 107]
 [ 49  59  60]]


In [ ]:
A = np.array([[3,5], [6,4]])

B = np.array([[3,7], [5,1]])


index_A = A[0,0] * B[0,0] + A[0,1] * B[1,0]
index_B = A[0,0] * B[0,1] + A[0,1] * B[1,1]
index_C = A[1,0] * B[0,0] + A[1,1] * B[1,0]
index_D = A[1,0] * B[0,1] + A[1,1] * B[1,1]


print(index_A)
print(index_B)
print(index_C)
print(index_D)

matmal = np.dot(A,B)
print(matmal)

34
26
38
46
[[34 26]
 [38 46]]
